[versions]
agp = "8.13.2"
bcprovJdk15on = "1.70"
bedrockConnection = "3.0.0.Beta10-SNAPSHOT"
espressoCore = "3.7.0"
appcompat = "1.7.1"
annotation = "1.9.1"
activityKtx = "1.12.2"
apkParser = "2.6.10"
browser = "1.9.0"
conscryptAndroid = "2.5.3"
constraintlayout = "2.2.1"
core = "1.58.0.0"
coreSplashscreen = "1.2.0"
firebase-iid = "21.1.0"
firebase-messaging = "25.0.1"
fragmentKtx = "1.8.9"
gamesActivity = "4.0.0"
gson = "2.13.2"
guava = "33.5.0-jre"
httpclient = "4.5.14"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.3.0"
lifecycle = "2.10.0"
material = "1.13.0"
okhttp = "5.3.2"
pkix = "1.54.0.0"
preference-ktx = "1.2.1"
roomRuntime = "2.8.4"
simpleXml = "2.7.1"
billing = "8.3.0"
sqliteFramework = "2.6.2"
dynamicanimation = "1.1.0"
xcrashAndroidLib = "3.1.0"

[libraries]
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-sqlite-framework = { module = "androidx.sqlite:sqlite-framework", version.ref = "sqliteFramework" }
annotations = { module = "org.jetbrains:annotations", version = "26.0.2-1" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
androidx-games-activity = { module = "androidx.games:games-activity", version.ref = "gamesActivity" }
androidx-lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version = "2.2.0" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
apk-parser = { module = "net.dongliu:apk-parser", version.ref = "apkParser" }
bcprov-jdk15on = { module = "org.bouncycastle:bcprov-jdk15on", version.ref = "bcprovJdk15on" }
bedrock-connection = { module = "org.cloudburstmc.protocol:bedrock-connection", version.ref = "bedrockConnection" }
conscrypt-android = { module = "org.conscrypt:conscrypt-android", version.ref = "conscryptAndroid" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
core = { module = "com.madgag.spongycastle:core", version.ref = "core" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
firebase-iid = { module = "com.google.firebase:firebase-iid", version.ref = "firebase-iid" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebase-messaging" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
httpclient = { module = "org.apache.httpcomponents:httpclient", version.ref = "httpclient" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
material = { module = "com.google.android.material:material", version.ref = "material" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
pkix = { module = "com.madgag.spongycastle:pkix", version.ref = "pkix" }
prov = { module = "com.madgag.spongycastle:prov", version.ref = "core" }
simple-xml = { group = "org.simpleframework", name = "simple-xml", version.ref = "simpleXml" }
billing = { group = "com.android.billingclient", name = "billing", version.ref = "billing" }
androidx-dynamicanimation = { module = "androidx.dynamicanimation:dynamicanimation", version.ref = "dynamicanimation" }
xcrash-android-lib = { module = "com.iqiyi.xcrash:xcrash-android-lib", version.ref = "xcrashAndroidLib" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

