name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      - name: Install Build Tools 35.0.0
        run: sdkmanager "build-tools;35.0.0"

      - name: Verify installed SDK Packages
        run: sdkmanager --list

      - name: Setup Xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: "2.9.9"
          actions-cache-folder: ".xmake-cache"
          actions-cache-key: "ubuntulinux-ci"

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c
          link-to-sdk: true

      - name: Grant Execute Permission to gradlew
        run: chmod +x ./gradlew

      - name: Inject API Keys
        env:
          CF_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        run: echo "curseforge.api_key=${CF_API_KEY}" >> local.properties

      - name: Build Debug, Beta and Unsigned Release APKs
        run: ./gradlew assembleDebug assembleBeta assembleRelease

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: LeviLauncher-debug-apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload Unsigned Release APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: LeviLauncher-release-unsigned-apk
          path: app/build/outputs/apk/release/*-unsigned.apk

      - name: Upload Beta APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: LeviLauncher-beta-apk
          path: app/build/outputs/apk/beta/*.apk

      - name: Sign Release APK
        if: startsWith(github.ref, 'refs/tags/')
        uses: kevin-david/zipalign-sign-android-release@v2
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY_STORE }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          zipAlign: true
        env:
          BUILD_TOOLS_VERSION: "35.0.0"

      - name: Rename APK with tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=${GITHUB_REF_NAME}
          SIGNED_APK="${{ steps.sign_app.outputs.signedReleaseFile }}"
          APK_DST="LeviLauncher-${TAG}-release.apk"
          cp "$SIGNED_APK" "$APK_DST"
          echo "Signed APK renamed to $APK_DST"

      - name: Upload Signed APK Artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4.6.2
        with:
          name: LeviLauncher-${{ github.ref_name }}-release.apk
          path: LeviLauncher-${{ github.ref_name }}-release.apk

      - name: Release APK to GitHub Releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: LeviLauncher-${{ github.ref_name }}-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Discord
        if: startsWith(github.ref, 'refs/tags/')
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          APK_URL: "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/LeviLauncher-${{ github.ref_name }}-release.apk"
          TAG_NAME: ${{ github.ref_name }}
        run: |
          EMBED_TITLE="ðŸš€ LeviLauncher Update!"
          EMBED_DESC="A new version of **LeviLaunchroid** is ready."
          EMBED_COLOR=5814783
          THUMB_URL='https://avatars.githubusercontent.com/u/78095377?s=200&v=4'

          curl -H "Content-Type: application/json" \
          -d "{
            \"embeds\": [{
              \"title\": \"$EMBED_TITLE\",
              \"description\": \"$EMBED_DESC\",
              \"color\": $EMBED_COLOR,
              \"thumbnail\": { \"url\": \"$THUMB_URL\" },
              \"fields\": [
                {
                  \"name\": \"ðŸ“¦ Version\",
                  \"value\": \"\`$TAG_NAME\`\",
                  \"inline\": true
                },
                {
                  \"name\": \"ðŸ”— Download\",
                  \"value\": \"[**Click here to download APK**]($APK_URL)\",
                  \"inline\": true
                }
              ]
            }]
          }" \
          "$DISCORD_WEBHOOK"
